# tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8999
  servlet:
    context-path: /emos-wx-api
spring:
  config:
    import: application-secret.yaml, application-value.yaml
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    default-encoding: UTF-8
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hjc.db.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
    com.hjc.db.dao: warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"
